include $(GOROOT)/src/Make.inc

TARGDIR=/usr/local/sbin
TARG=player
GCIMPORTS=-I../pkg/_obj
LDIMPORTS=-L../pkg/_obj

GOFILES=\
	player.go\
	scores.go\
	execution.go\
	interface.go\
	if_env.go\

include $(GOROOT)/src/Make.cmd
